name: rl
channels:
  - menpo
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.26.0=hd590300_0
  - ca-certificates=2024.2.2=hbcca054_0
  - comm=0.2.1=pyhd8ed1ab_0
  - debugpy=1.8.1=py38h17151c0_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - elfutils=0.190=h924a536_1
  - executing=2.0.1=pyhd8ed1ab_0
  - gettext=0.21.1=h27087fc_0
  - glew=2.0.0=0
  - glfw3=3.2.1=0
  - gnutls=3.7.9=hb077bed_0
  - icu=73.2=h59595ed_0
  - importlib-metadata=7.0.1=pyha770c72_0
  - importlib_metadata=7.0.1=hd8ed1ab_0
  - ipykernel=6.29.2=pyhd33586a_0
  - ipython=8.12.2=pyh41d4057_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=8.6.0=pyhd8ed1ab_0
  - jupyter_core=5.7.1=py38h578d9bd_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.21.2=h659d440_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libarchive=3.7.2=h2aa1ff5_1
  - libcurl=8.5.0=hca28451_0
  - libdrm=2.4.120=hd590300_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_5
  - libglu=9.0.0=hac7e632_1003
  - libgomp=13.2.0=h807b86a_5
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.7=hd590300_0
  - libllvm17=17.0.6=hb3ce162_1
  - libmicrohttpd=1.0.0=h97afed2_0
  - libnghttp2=1.58.0=h47da74e_1
  - libnsl=2.0.1=hd590300_0
  - libpciaccess=0.18=hd590300_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.45.1=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libtasn1=4.19.0=h166bdaf_0
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.5=h232c23b_0
  - libzlib=1.2.13=hd590300_5
  - lz4-c=1.9.4=hcb278e6_0
  - lzo=2.10=h516909a_1000
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mesalib=24.0.1=hf257a20_0
  - ncurses=6.4=h59595ed_2
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - nettle=3.9.1=h7ab15ed_0
  - openssl=3.2.1=hd590300_0
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=23.2=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=24.0=pyhd8ed1ab_0
  - platformdirs=4.2.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - prompt_toolkit=3.0.42=hd8ed1ab_0
  - psutil=5.9.8=py38h01eb140_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - python=3.8.18=hd12c33a_1_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=4_cp38
  - pyzmq=25.1.2=py38h34c975a_0
  - readline=8.2=h8228510_1
  - setuptools=69.1.0=pyhd8ed1ab_1
  - six=1.16.0=pyh6c4a22f_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.4=py38h01eb140_0
  - traitlets=5.14.1=pyhd8ed1ab_0
  - typing_extensions=4.9.0=pyha770c72_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - xorg-damageproto=1.2.1=h7f98852_1002
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-glproto=1.4.17=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libx11=1.8.7=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdamage=1.1.5=h7f98852_1
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxrandr=1.5.2=h7f98852_1
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-randrproto=1.5.0=h7f98852_1001
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-util-macros=1.19.3=h7f98852_0
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xf86vidmodeproto=2.3.1=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - zeromq=4.3.5=h59595ed_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zstd=1.5.5=hfc55251_0
  - pip:
      - absl-py==2.1.0
      - certifi==2024.2.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==3.0.0
      - colorama==0.4.4
      - contourpy==1.1.1
      - cycler==0.12.1
      - cython==3.0.0a10
      - dm-control==1.0.16
      - dm-env==1.6
      - dm-tree==0.1.8
      - etils==1.3.0
      - fasteners==0.19
      - filelock==3.9.0
      - fonttools==4.49.0
      - fsspec==2023.4.0
      - glfw==2.6.5
      - gym==0.23.1
      - gym-notices==0.0.8
      - h5py==3.10.0
      - idna==3.6
      - imageio==2.34.0
      - importlib-resources==6.1.1
      - jinja2==3.1.2
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - labmaze==1.0.6
      - lxml==5.1.0
      - markupsafe==2.1.3
      - matplotlib==3.7.5
      - mjrl==1.0.0
      - mpmath==1.3.0
      - mujoco==3.1.2
      - mujoco-py==2.1.2.14
      - networkx==3.0
      - normflows==1.7.3
      - numpy==1.24.4
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==8.7.0.84
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.19.3
      - nvidia-nvtx-cu11==11.8.86
      - pandas==2.0.3
      - patchelf==0.17.2.1
      - pillow==10.2.0
      - protobuf==4.25.3
      - pybullet==3.2.6
      - pycparser==2.21
      - pyopengl==3.1.7
      - pyparsing==3.1.1
      - pytz==2024.1
      - requests==2.31.0
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - sympy==1.12
      - tensorboard==2.16.2
      - termcolor==2.4.0
      - threadpoolctl==3.5.0
      - torch==2.2.0+cu118
      - torchaudio==2.2.0+cu118
      - torchvision==0.17.0+cu118
      - tqdm==4.66.2
      - triton==2.2.0
      - tzdata==2024.1
      - urllib3==2.2.1
